apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: githttpserver
spec:
  selector:
    app: githttpserver
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: githttpserver
spec:
  selector:
    matchLabels:
      app: githttpserver
  serviceName: "githttpserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: githttpserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: githttpserver
        image: psalomo/githttpserver:0.0.4
        volumeMounts:
        - mountPath: /mnt/gitrepos
          name: gitreposvolume
        env:
          - name: GIT_PROJECT_ROOT
            value: /mnt/gitrepos
      volumes:
      - name: gitreposvolume
        persistentVolumeClaim:
          claimName: gitvolume
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: githttpserverdemo
  annotations:    
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:   
  - http:
      paths:
      - path: /
        backend:
          serviceName: githttpserver
          servicePort: 5000